name: backend-cd

on:
  workflow_run:
    workflows: ["backend-ci"]
    types: [completed]

permissions:
  id-token: write # REQUIRED for OIDC
  contents: read # REQUIRED for checkout (if used)

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::928558116854:role/ECRPushCICD
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Pull image from Docker Hub
        run: |
          docker pull sanjayramagiri99/backend:${{ github.event.workflow_run.head_sha }}

      - name: Tag & Push to ECR
        run: |
          docker tag sanjayramagiri99/backend:${{ github.event.workflow_run.head_sha }} \
          928558116854.dkr.ecr.us-east-1.amazonaws.com/docker-project/new:backend-${{ github.event.workflow_run.head_sha }}

          docker push 928558116854.dkr.ecr.us-east-1.amazonaws.com/docker-project/new:backend-${{ github.event.workflow_run.head_sha }}
